export const navigation = [
    {
        type: 'link',
        label: 'Dashboard',
        routeName: 'dashboard',
        iconKey: 'dashboard',
        activePatterns: ['/dashboard'],
        ability: null,
        roles: null,
    },
    {
        type: 'link',
        label: 'Employees',
        routeName: 'employees.index',
        iconKey: 'employees',
        activePatterns: ['/employees'],
        ability: 'accessEmployees',
        roles: null,
    },
    {
        type: 'link',
        label: 'Departments',
        routeName: 'departments.index',
        iconKey: 'employees',
        activePatterns: ['/departments'],
        ability: 'accessEmployees',
        roles: null,
    },
    {
        type: 'link',
        label: 'Recruitment',
        routeName: 'recruitment.index',
        iconKey: 'recruitment',
        activePatterns: ['/recruitment'],
        ability: 'accessRecruitment',
        roles: null,
    },
    {
        type: 'link',
        label: 'Leave Requests',
        routeName: 'leave.requests.index',
        iconKey: 'employees',
        activePatterns: ['/leave/requests'],
        ability: 'accessLeaves',
        roles: null,
    },
    {
        type: 'link',
        label: 'Leave Types',
        routeName: 'leave.types.index',
        iconKey: 'employees',
        activePatterns: ['/leave/types'],
        ability: 'manageLeaveTypes',
        roles: null,
    },
    {
        type: 'group',
        label: 'Account Management',
        iconKey: 'account',
        children: [
            {
                label: 'User',
                routeName: 'users.index',
                iconKey: 'users',
                activePatterns: ['/users'],
                ability: 'manageUsers',
            },
            {
                label: 'Role',
                routeName: 'roles.index',
                iconKey: 'roles',
                activePatterns: ['/roles'],
                ability: 'manageRoles',
            },
            {
                label: 'Modules & Permissions',
                routeName: 'permissions.index',
                iconKey: 'lock',
                activePatterns: ['/permissions'],
                ability: 'manageRoles',
            },
        ],
    },
];
