export const navigation = [
    {
        type: 'link',
        label: 'Dashboard',
        routeName: 'dashboard',
        iconKey: 'dashboard',
        activePatterns: ['/dashboard'],
        ability: null,
        roles: ['admin', 'hr', 'manager'],
    },
    {
        type: 'link',
        label: 'My Profile',
        routeName: 'my.profile',
        iconKey: 'account',
        activePatterns: ['/my/profile'],
        ability: 'accessMyPortal',
        roles: ['employee'],
    },
    {
        type: 'link',
        label: 'My Leave',
        routeName: 'my.leave.index',
        iconKey: 'leave',
        activePatterns: ['/my/leave'],
        ability: 'accessMyPortal',
        roles: ['employee'],
    },
    {
        type: 'link',
        label: 'My Attendance (Daily)',
        routeName: 'my.attendance.daily',
        iconKey: 'attendance',
        activePatterns: ['/my/attendance/daily'],
        ability: 'accessMyPortal',
        roles: ['employee'],
    },
    {
        type: 'link',
        label: 'My Attendance (Monthly)',
        routeName: 'my.attendance.monthly',
        iconKey: 'attendance',
        activePatterns: ['/my/attendance/monthly'],
        ability: 'accessMyPortal',
        roles: ['employee'],
    },
    {
        type: 'link',
        label: 'Employees',
        routeName: 'employees.index',
        iconKey: 'employees',
        activePatterns: ['/employees'],
        ability: 'accessEmployees',
        roles: null,
    },
    {
        type: 'link',
        label: 'Departments',
        routeName: 'departments.index',
        iconKey: 'departments',
        activePatterns: ['/departments'],
        ability: 'accessEmployees',
        roles: null,
    },
    {
        type: 'link',
        label: 'Recruitment',
        routeName: 'recruitment.index',
        iconKey: 'recruitment',
        activePatterns: ['/recruitment'],
        ability: 'accessRecruitment',
        roles: null,
    },
    {
        type: 'link',
        label: 'Leave Requests',
        routeName: 'leave.requests.index',
        iconKey: 'leave',
        activePatterns: ['/leave/requests'],
        ability: 'accessLeaves',
        roles: null,
    },
    {
        type: 'link',
        label: 'Leave Types',
        routeName: 'leave.types.index',
        iconKey: 'leave_types',
        activePatterns: ['/leave/types'],
        ability: 'manageLeaveTypes',
        roles: null,
    },
    {
        type: 'link',
        label: 'Attendance (Daily)',
        routeName: 'attendance.daily',
        iconKey: 'attendance',
        activePatterns: ['/attendance/daily'],
        ability: 'accessAttendance',
        roles: null,
    },
    {
        type: 'link',
        label: 'Attendance (Monthly)',
        routeName: 'attendance.monthly',
        iconKey: 'attendance',
        activePatterns: ['/attendance/monthly'],
        ability: 'accessAttendance',
        roles: null,
    },
    {
        type: 'link',
        label: 'Payroll Summary',
        routeName: 'payroll.summary.index',
        iconKey: 'payroll',
        activePatterns: ['/payroll/summary'],
        ability: 'accessPayrollSummary',
        roles: null,
    },
    {
        type: 'link',
        label: 'Chat',
        routeName: 'chat.index',
        iconKey: 'chat',
        activePatterns: ['/chat'],
        ability: null,
        roles: ['admin', 'hr', 'manager', 'employee'],
    },
    {
        type: 'group',
        label: 'Account Management',
        iconKey: 'account',
        children: [
            {
                label: 'User',
                routeName: 'users.index',
                iconKey: 'users',
                activePatterns: ['/users'],
                ability: 'manageUsers',
            },
            {
                label: 'Role',
                routeName: 'roles.index',
                iconKey: 'roles',
                activePatterns: ['/roles'],
                ability: 'manageRoles',
            },
            {
                label: 'Modules & Permissions',
                routeName: 'permissions.index',
                iconKey: 'lock',
                activePatterns: ['/permissions'],
                ability: 'manageRoles',
            },
        ],
    },
    {
        type: 'group',
        label: 'HR Settings',
        iconKey: 'settings',
        children: [
            {
                label: 'Memo Templates',
                routeName: 'settings.memo_templates.index',
                iconKey: 'memo',
                activePatterns: ['/settings/memo-templates'],
                ability: 'manageMemoTemplates',
            },
        ],
    },
    {
        type: 'group',
        label: 'Developer Settings',
        iconKey: 'lock',
        children: [
            {
                label: 'Audit Logs',
                routeName: 'developer.audit-logs.index',
                iconKey: 'lock',
                activePatterns: ['/developer/audit-logs'],
                ability: 'accessDeveloper',
                roles: ['admin', 'hr', 'manager', 'employee'],
            },
            {
                label: 'Companies',
                routeName: 'developer.companies.index',
                iconKey: 'lock',
                activePatterns: ['/developer/companies'],
                ability: 'accessDeveloper',
                roles: ['admin', 'hr', 'manager', 'employee'],
            },
            {
                label: 'Demo requests',
                routeName: 'developer.demo_requests.index',
                iconKey: 'lock',
                activePatterns: ['/developer/demo-requests'],
                ability: 'accessDeveloper',
                roles: ['admin', 'hr', 'manager', 'employee'],
            },
        ],
    },
];
